spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/team_f_test
    username : root
    password : green502

#my batis config
mybatis:
  type-aliases-package: com.example.board6
  mapper-locations: mappers/**/*.xml


springdoc:
  swagger-ui:
    path: /swagger.html

file:
   dir: D:/download/board6